; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc1-n4r2]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board_build.partitions = max_app_4MB.csv
board = esp32-s3-devkitc-1
monitor_speed = 115200
monitor_eol = LF
monitor_dtr = 0
framework = arduino
lib_deps = 
	adafruit/Adafruit TLV320 I2S@^1.0.0
	yellobyte/TLV320DAC3101@^1.3.1
	haklein/tlv320aic31xx@^1.0.5
	https://github.com/pschatzmann/arduino-audio-tools.git
	https://github.com/pschatzmann/arduino-libhelix.git
	https://github.com/pschatzmann/ESP32-A2DP
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	; -DCORE_DEBUG_LEVEL=5 -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format-extra-args 
monitor_filters = esp32_exception_decoder